// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBnLmMTFV0rn3AnrKgdcaCpKUdfX3wVfM',
    appId: '1:923250330581:web:dc7047f2af122b281e8b5c',
    messagingSenderId: '923250330581',
    projectId: 'vue-firebase-gia',
    authDomain: 'vue-firebase-gia.firebaseapp.com',
    storageBucket: 'vue-firebase-gia.appspot.com',
    measurementId: 'G-RRB8RYF2N5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDEXvg6A7O-xJ4Gzk7r_YSHSEDT1wqZss',
    appId: '1:923250330581:android:d3defade0958f49b1e8b5c',
    messagingSenderId: '923250330581',
    projectId: 'vue-firebase-gia',
    storageBucket: 'vue-firebase-gia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeNYXlpSmLkbWyddglJ5XANXgU9pDagUk',
    appId: '1:923250330581:ios:947b44d50108c8831e8b5c',
    messagingSenderId: '923250330581',
    projectId: 'vue-firebase-gia',
    storageBucket: 'vue-firebase-gia.appspot.com',
    iosClientId: '923250330581-ourc40rgvd9ncvbbfigli48j45bfnn2i.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeNYXlpSmLkbWyddglJ5XANXgU9pDagUk',
    appId: '1:923250330581:ios:b89de316e4f6a5b31e8b5c',
    messagingSenderId: '923250330581',
    projectId: 'vue-firebase-gia',
    storageBucket: 'vue-firebase-gia.appspot.com',
    iosClientId: '923250330581-22rce54evj03go022uq3dnhb52gap4uh.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone.RunnerTests',
  );
}
